export const pricingCatalog = {
  version: "2026-08-25",
  plans: {
    free: {
      name: "Free",
      monthlyPrice: 0,
      commitmentMonthlyPrice: 0,
      monthlyCredits: "1,200",
      workspaces: "1",
      deployedWorkflows: "2",
      tables: "3",
      rowsPerTable: "1,000",
      runHistory: "1 day",
      premiumWorkflowNodes: "No",
      exclusiveAiModels: "No",
    },
    pro: {
      name: "Pro",
      monthlyPrice: 19.99,
      commitmentMonthlyPrice: 16.99,
      commitmentValue: 203.88,
      monthlyCredits: "10,000",
      workspaces: "3",
      deployedWorkflows: "Unlimited",
      tables: "25",
      rowsPerTable: "5,000",
      runHistory: "30 days",
      premiumWorkflowNodes: "Yes",
      exclusiveAiModels: "No",
    },
    business: {
      name: "Business",
      monthlyPrice: 199.99,
      commitmentMonthlyPrice: 169.99,
      commitmentValue: 2039.88,
      monthlyCredits: "140,000",
      workspaces: "Unlimited",
      deployedWorkflows: "Unlimited",
      tables: "Unlimited",
      rowsPerTable: "50,000",
      runHistory: "90 days",
      premiumWorkflowNodes: "Yes",
      exclusiveAiModels: "Yes",
    },
    enterprise: {
      name: "Enterprise",
      monthlyPrice: null,
      commitmentMonthlyPrice: null,
      monthlyCredits: "Custom",
      workspaces: "Custom",
      deployedWorkflows: "Custom",
      tables: "Custom",
      rowsPerTable: "Custom",
      runHistory: "Custom",
      premiumWorkflowNodes: "Yes",
      exclusiveAiModels: "Yes",
    },
  },
} as const;
