export type IndustryWorkflow = {
  label: string;
  title: string;
  body: string;
  input: string;
  context: string;
  output: string;
};
export type IndustryPageContent = {
  slug: string;
  name: string;
  group: "industry" | "solution";
  headline: string;
  description: string;
  request: string;
  team: string;
  steps: string[];
  surface: string;
  workflows: IndustryWorkflow[];
};

// Original Innflow copy. Workflow examples describe starting points, not customer results.
export const industryPages: IndustryPageContent[] = [
  {
    slug: "financial-services-banking",
    name: "Financial Services & Banking",
    group: "industry",
    headline: "Keep financial work moving, with context.",
    description:
      "Connect client requests, document preparation and team handoffs across financial operations.",
    request: "A client needs an update on an account request.",
    team: "Account service team",
    steps: [
      "Confirm the account context",
      "Prepare the service summary",
      "Review the next action",
    ],
    surface: "#d3e5ff",
    workflows: [
      {
        label: "Client requests",
        title: "Give every client request a clear owner.",
        body: "Gather the conversation and supporting information before routing the request to the responsible team.",
        input: "Account question",
        context: "Client context",
        output: "Assigned service owner",
      },
      {
        label: "Document preparation",
        title: "Find the missing pieces before review.",
        body: "Organize requested documents and highlight outstanding items so the next reviewer knows what is ready.",
        input: "Submitted documents",
        context: "Missing-item checklist",
        output: "Prepared review pack",
      },
      {
        label: "Operational handoffs",
        title: "Carry the context into the next team.",
        body: "Keep the request, open questions and next steps together as work moves between service and operations.",
        input: "Service handoff",
        context: "Open questions",
        output: "Operations follow-up",
      },
    ],
  },
  {
    slug: "finance",
    name: "Finance",
    group: "industry",
    headline: "Make room for the work behind the numbers.",
    description:
      "Bring invoice questions, reporting inputs and finance follow-ups into a shared flow.",
    request: "An invoice is waiting for supporting documentation.",
    team: "Finance operations",
    steps: [
      "Collect the invoice context",
      "Identify the missing document",
      "Review the follow-up",
    ],
    surface: "#eae3f9",
    workflows: [
      {
        label: "Invoice coordination",
        title: "Keep invoice questions out of scattered threads.",
        body: "Group the request, supporting files and responsible person before preparing the next response.",
        input: "Invoice query",
        context: "Supporting files",
        output: "Owner review",
      },
      {
        label: "Reporting preparation",
        title: "Bring the inputs together before reporting starts.",
        body: "Track requested inputs and unresolved questions in one place for the person preparing the report.",
        input: "Reporting request",
        context: "Input checklist",
        output: "Preparation summary",
      },
      {
        label: "Vendor follow-ups",
        title: "Make the next step clear to everyone.",
        body: "Prepare a follow-up from the current conversation and keep payment decisions with the finance team.",
        input: "Vendor message",
        context: "Current status",
        output: "Draft follow-up",
      },
    ],
  },
  {
    slug: "banking",
    name: "Banking",
    group: "industry",
    headline: "A clearer path for every service request.",
    description:
      "Help banking teams coordinate service conversations, onboarding preparation and internal follow-ups.",
    request: "A customer asks what is missing from their onboarding pack.",
    team: "Customer service",
    steps: [
      "Gather the submitted items",
      "Prepare a missing-item summary",
      "Send for staff review",
    ],
    surface: "#f1f8dc",
    workflows: [
      {
        label: "Onboarding coordination",
        title: "Make preparation easier to follow.",
        body: "Organize requested information and route gaps to the right person before account review.",
        input: "Onboarding request",
        context: "Document checklist",
        output: "Staff review",
      },
      {
        label: "Account servicing",
        title: "Keep the customer conversation connected.",
        body: "Bring prior messages and open questions into a service handoff so the team can pick up with context.",
        input: "Customer question",
        context: "Conversation summary",
        output: "Service handoff",
      },
      {
        label: "Internal requests",
        title: "Route operational questions to the right desk.",
        body: "Assign internal requests with clear context and track what needs an answer.",
        input: "Branch request",
        context: "Owner assignment",
        output: "Response preparation",
      },
    ],
  },
  {
    slug: "insurance",
    name: "Insurance",
    group: "industry",
    headline: "Bring clarity to every policy conversation.",
    description:
      "Keep policy questions, claims correspondence and renewal preparation connected to the people handling them.",
    request: "A policyholder sends supporting information for a claim.",
    team: "Claims coordination",
    steps: [
      "Organize the correspondence",
      "Identify outstanding information",
      "Route to the claims team",
    ],
    surface: "#e5f9f9",
    workflows: [
      {
        label: "Claims coordination",
        title: "Give the next reviewer a complete picture.",
        body: "Collect correspondence and organize supporting items for the person responsible for the claim.",
        input: "Incoming correspondence",
        context: "Document summary",
        output: "Claims-team handoff",
      },
      {
        label: "Policy questions",
        title: "Help your team respond with context.",
        body: "Bring the question and relevant approved information together before a response is reviewed.",
        input: "Policy question",
        context: "Reference material",
        output: "Response draft",
      },
      {
        label: "Renewal preparation",
        title: "Keep renewal conversations moving.",
        body: "Track open questions, requested information and the next owner as a renewal approaches.",
        input: "Renewal conversation",
        context: "Outstanding questions",
        output: "Assigned follow-up",
      },
    ],
  },
  {
    slug: "healthcare",
    name: "Healthcare",
    group: "industry",
    headline: "More clarity around the work of care.",
    description:
      "Coordinate administrative requests, appointment questions and office handoffs so staff can focus on the next step.",
    request: "A patient asks how to prepare for an upcoming appointment.",
    team: "Administrative team",
    steps: [
      "Identify the administrative request",
      "Find approved instructions",
      "Prepare a staff-reviewed reply",
    ],
    surface: "#d3e5ff",
    workflows: [
      {
        label: "Appointment coordination",
        title: "Make appointment questions easier to manage.",
        body: "Organize scheduling requests and route changes to the appropriate administrative team.",
        input: "Appointment question",
        context: "Scheduling context",
        output: "Office follow-up",
      },
      {
        label: "Administrative intake",
        title: "Give incoming requests a clear destination.",
        body: "Classify administrative messages and keep missing information visible to staff.",
        input: "Office request",
        context: "Request summary",
        output: "Assigned team",
      },
      {
        label: "Office knowledge",
        title: "Keep approved information close at hand.",
        body: "Help staff locate office instructions and prepare consistent administrative responses.",
        input: "Preparation question",
        context: "Approved instructions",
        output: "Staff-reviewed reply",
      },
    ],
  },
  {
    slug: "retail-ecommerce",
    name: "Retail & eCommerce",
    group: "industry",
    headline: "Keep the conversation moving after checkout.",
    description:
      "Bring order questions, return requests and customer follow-ups into a connected service workflow.",
    request: "A customer asks about returning an item from a recent order.",
    team: "Customer care",
    steps: [
      "Gather the order question",
      "Find the applicable return guidance",
      "Prepare a response for review",
    ],
    surface: "#eae3f9",
    workflows: [
      {
        label: "Order questions",
        title: "Find the context behind each order inquiry.",
        body: "Keep customer messages and supplied order details together as your team investigates.",
        input: "Order inquiry",
        context: "Conversation context",
        output: "Service response",
      },
      {
        label: "Return coordination",
        title: "Give return requests a clear next step.",
        body: "Prepare the request and relevant policy information for the person reviewing the return.",
        input: "Return request",
        context: "Policy reference",
        output: "Review handoff",
      },
      {
        label: "Customer feedback",
        title: "Spot questions that keep coming back.",
        body: "Group related feedback so product and service teams can see what deserves attention.",
        input: "Customer feedback",
        context: "Related conversations",
        output: "Team summary",
      },
    ],
  },
  {
    slug: "property-real-estate",
    name: "Property & Real Estate",
    group: "industry",
    headline: "Connect the people behind every property.",
    description:
      "Bring property inquiries, transaction coordination and document follow-ups into one shared workflow.",
    request: "A prospective buyer requests information about a property.",
    team: "Property advisory",
    steps: [
      "Gather the inquiry",
      "Prepare the property context",
      "Assign the next conversation",
    ],
    surface: "#f1f8dc",
    workflows: [
      {
        label: "Property inquiries",
        title: "Turn interest into a clear follow-up.",
        body: "Collect the inquiry and relevant property information before handing it to the right person.",
        input: "Property inquiry",
        context: "Property context",
        output: "Advisor follow-up",
      },
      {
        label: "Transaction coordination",
        title: "Keep open items visible between teams.",
        body: "Organize requested documents and outstanding questions around each transaction.",
        input: "Transaction request",
        context: "Open-item checklist",
        output: "Team handoff",
      },
      {
        label: "Document follow-ups",
        title: "Help the next reviewer get oriented.",
        body: "Gather supporting information and prepare a summary without losing the original correspondence.",
        input: "Document request",
        context: "Supporting context",
        output: "Review summary",
      },
    ],
  },
  {
    slug: "property-management",
    name: "Property Management",
    group: "industry",
    headline: "A clearer day in property operations.",
    description:
      "Keep resident conversations, maintenance coordination and owner updates connected to your team.",
    request: "A resident reports a maintenance issue in their apartment.",
    team: "Property operations",
    steps: [
      "Collect the issue details",
      "Identify the responsible team",
      "Prepare the maintenance handoff",
    ],
    surface: "#e5f9f9",
    workflows: [
      {
        label: "Resident communication",
        title: "Pick up every conversation with context.",
        body: "Bring the resident request, property details and prior messages into the next response.",
        input: "Resident message",
        context: "Property context",
        output: "Response draft",
      },
      {
        label: "Maintenance coordination",
        title: "Give each issue an owner.",
        body: "Gather issue details and route the next step to your team for review and assignment.",
        input: "Maintenance request",
        context: "Issue summary",
        output: "Team assignment",
      },
      {
        label: "Owner updates",
        title: "Make progress easier to explain.",
        body: "Prepare an update from open questions and operational activity for your team to review.",
        input: "Update request",
        context: "Activity summary",
        output: "Owner communication",
      },
    ],
  },
  {
    slug: "manufacturing",
    name: "Manufacturing",
    group: "industry",
    headline: "Keep operational handoffs in motion.",
    description:
      "Connect supplier questions, production support requests and quality documentation across your teams.",
    request: "A production team needs an update on a supplier issue.",
    team: "Operations coordination",
    steps: [
      "Capture the issue",
      "Collect the supplier conversation",
      "Route the next action",
    ],
    surface: "#d3e5ff",
    workflows: [
      {
        label: "Supplier coordination",
        title: "Keep supplier questions tied to the work.",
        body: "Organize messages and open questions so purchasing and operations share the same context.",
        input: "Supplier message",
        context: "Open questions",
        output: "Purchasing handoff",
      },
      {
        label: "Production support",
        title: "Route requests without losing the details.",
        body: "Prepare an issue summary and assign the responsible team for investigation.",
        input: "Support request",
        context: "Issue summary",
        output: "Team assignment",
      },
      {
        label: "Quality documentation",
        title: "Bring the evidence together for review.",
        body: "Collect requested information and identify missing items before a quality reviewer takes over.",
        input: "Documentation request",
        context: "Evidence checklist",
        output: "Reviewer handoff",
      },
    ],
  },
  {
    slug: "telecommunications",
    name: "Telecommunications",
    group: "industry",
    headline: "Connect service conversations to action.",
    description:
      "Bring account questions, installation coordination and service escalations into a shared operational flow.",
    request: "A customer asks for an update on an installation appointment.",
    team: "Service operations",
    steps: [
      "Gather the appointment question",
      "Prepare the service context",
      "Route to the coordination team",
    ],
    surface: "#eae3f9",
    workflows: [
      {
        label: "Service inquiries",
        title: "Keep the full conversation in view.",
        body: "Prepare the customer question and prior correspondence for a more informed response.",
        input: "Service message",
        context: "Conversation summary",
        output: "Team response",
      },
      {
        label: "Installation coordination",
        title: "Make the next appointment step clear.",
        body: "Organize scheduling questions and outstanding information for the installation team.",
        input: "Installation question",
        context: "Scheduling context",
        output: "Coordinator follow-up",
      },
      {
        label: "Escalation handoffs",
        title: "Give the next team a useful starting point.",
        body: "Summarize the issue, actions already taken and questions still awaiting an answer.",
        input: "Escalated request",
        context: "Actions taken",
        output: "Specialist handoff",
      },
    ],
  },
  {
    slug: "professional-services",
    name: "Professional Services",
    group: "industry",
    headline: "Keep client work connected from the start.",
    description:
      "Organize client intake, project communication and deliverable reviews around the people doing the work.",
    request: "A new client sends requirements for an upcoming project.",
    team: "Client delivery",
    steps: [
      "Collect the project context",
      "Prepare the intake summary",
      "Assign the delivery owner",
    ],
    surface: "#f1f8dc",
    workflows: [
      {
        label: "Client intake",
        title: "Start with a shared understanding.",
        body: "Gather requirements and open questions before handing the engagement to the delivery team.",
        input: "Client brief",
        context: "Intake summary",
        output: "Delivery handoff",
      },
      {
        label: "Project updates",
        title: "Bring the next conversation up to speed.",
        body: "Prepare updates from project correspondence and outstanding actions for team review.",
        input: "Update request",
        context: "Project context",
        output: "Client-ready draft",
      },
      {
        label: "Deliverable reviews",
        title: "Keep feedback close to the work.",
        body: "Collect review comments and route the next revision to its owner.",
        input: "Review comments",
        context: "Action summary",
        output: "Revision assignment",
      },
    ],
  },
  {
    slug: "business-process-outsourcing",
    name: "Business Process Outsourcing",
    group: "industry",
    headline: "Make every handoff feel like one team.",
    description:
      "Connect client instructions, incoming work and review steps across outsourced operations.",
    request: "A client sends a new request with updated handling instructions.",
    team: "Delivery operations",
    steps: [
      "Identify the client workflow",
      "Gather the current instructions",
      "Prepare the team handoff",
    ],
    surface: "#e5f9f9",
    workflows: [
      {
        label: "Request intake",
        title: "Route incoming work with the right context.",
        body: "Identify the request and attach relevant client instructions before assigning it.",
        input: "Client request",
        context: "Handling instructions",
        output: "Assigned queue",
      },
      {
        label: "Delivery reviews",
        title: "Keep review steps visible.",
        body: "Prepare the work summary and outstanding questions for the person checking the result.",
        input: "Completed task",
        context: "Review checklist",
        output: "Reviewer handoff",
      },
      {
        label: "Client updates",
        title: "Keep customers informed about the next step.",
        body: "Gather current activity and open items into a draft update for the account team.",
        input: "Status request",
        context: "Activity summary",
        output: "Account-team review",
      },
    ],
  },
  {
    slug: "public-sector",
    name: "Public Sector",
    group: "industry",
    headline: "Give every public request a clear path.",
    description:
      "Help service teams coordinate inquiries, document requests and departmental handoffs.",
    request:
      "A resident asks which documents are needed for a service application.",
    team: "Public service team",
    steps: [
      "Identify the service request",
      "Find the approved guidance",
      "Prepare a reviewed response",
    ],
    surface: "#d3e5ff",
    workflows: [
      {
        label: "Public inquiries",
        title: "Make service information easier to find.",
        body: "Prepare responses using approved guidance and keep unresolved questions with the responsible team.",
        input: "Service inquiry",
        context: "Approved guidance",
        output: "Staff review",
      },
      {
        label: "Application coordination",
        title: "Keep missing information visible.",
        body: "Organize supplied items and requested documents before staff review an application.",
        input: "Application question",
        context: "Document checklist",
        output: "Staff handoff",
      },
      {
        label: "Departmental handoffs",
        title: "Carry the request across team boundaries.",
        body: "Summarize the inquiry and route it to the department responsible for the next action.",
        input: "Incoming request",
        context: "Request summary",
        output: "Department assignment",
      },
    ],
  },
  {
    slug: "energy-utilities",
    name: "Energy & Utilities",
    group: "industry",
    headline: "Keep service teams and customers connected.",
    description:
      "Bring service inquiries, field coordination and account follow-ups into a clearer workflow.",
    request: "A customer requests an update on a scheduled service visit.",
    team: "Service coordination",
    steps: [
      "Collect the service question",
      "Prepare the visit context",
      "Assign the follow-up",
    ],
    surface: "#eae3f9",
    workflows: [
      {
        label: "Customer inquiries",
        title: "Bring account questions into one flow.",
        body: "Gather correspondence and prepare the question for the right service team.",
        input: "Customer question",
        context: "Service context",
        output: "Team response",
      },
      {
        label: "Field coordination",
        title: "Help the next team arrive with context.",
        body: "Organize visit requests and outstanding details for field coordinators to review.",
        input: "Visit request",
        context: "Preparation checklist",
        output: "Coordinator handoff",
      },
      {
        label: "Service updates",
        title: "Make outstanding actions easier to follow.",
        body: "Prepare customer updates from the information supplied by your operations team.",
        input: "Update request",
        context: "Operations summary",
        output: "Reviewed communication",
      },
    ],
  },
  {
    slug: "construction",
    name: "Construction",
    group: "industry",
    headline: "Keep project conversations connected to the job.",
    description:
      "Coordinate project questions, subcontractor follow-ups and document reviews across office and site teams.",
    request: "A site team needs clarification on a project document.",
    team: "Project coordination",
    steps: [
      "Capture the question",
      "Gather the document context",
      "Route to the responsible reviewer",
    ],
    surface: "#f1f8dc",
    workflows: [
      {
        label: "Project questions",
        title: "Give every clarification a clear owner.",
        body: "Keep the question and supporting information together as it moves to the right reviewer.",
        input: "Site question",
        context: "Document reference",
        output: "Reviewer assignment",
      },
      {
        label: "Subcontractor follow-ups",
        title: "Make handoffs easier to track.",
        body: "Collect outstanding items and prepare the next follow-up for the project team.",
        input: "Subcontractor message",
        context: "Open-item summary",
        output: "Project follow-up",
      },
      {
        label: "Document coordination",
        title: "Keep review context close to the file.",
        body: "Prepare requested documents and associated questions for the next review step.",
        input: "Document submission",
        context: "Review context",
        output: "Team handoff",
      },
    ],
  },
  {
    slug: "supply-chain-logistics",
    name: "Supply Chain & Logistics",
    group: "industry",
    headline: "Keep the next handoff connected.",
    description:
      "Bring shipment questions, supplier coordination and delivery exceptions into one operational conversation.",
    request: "A customer asks for clarification about a delayed delivery.",
    team: "Logistics coordination",
    steps: [
      "Capture the delivery question",
      "Gather available shipment context",
      "Prepare the customer follow-up",
    ],
    surface: "#e5f9f9",
    workflows: [
      {
        label: "Shipment inquiries",
        title: "Help your team find the next answer.",
        body: "Group the customer question and available shipment details before preparing a response.",
        input: "Shipment question",
        context: "Available context",
        output: "Response draft",
      },
      {
        label: "Supplier coordination",
        title: "Keep outstanding items in view.",
        body: "Collect supplier messages and assign follow-ups to the person responsible for the next step.",
        input: "Supplier message",
        context: "Outstanding items",
        output: "Owner assignment",
      },
      {
        label: "Delivery exceptions",
        title: "Give exceptions a clear route forward.",
        body: "Summarize the reported issue and carry the context to the team investigating it.",
        input: "Delivery issue",
        context: "Exception summary",
        output: "Operations handoff",
      },
    ],
  },
  {
    slug: "hospitality-travel",
    name: "Hospitality & Travel",
    group: "industry",
    headline: "Make every guest conversation easier to follow.",
    description:
      "Connect booking questions, guest requests and operational handoffs across your team.",
    request: "A guest asks about arrival arrangements for an upcoming stay.",
    team: "Guest services",
    steps: [
      "Gather the arrival question",
      "Find approved guest information",
      "Prepare a personal response",
    ],
    surface: "#d3e5ff",
    workflows: [
      {
        label: "Booking inquiries",
        title: "Start each response with the right context.",
        body: "Bring the guest question and supplied booking details together for your reservations team.",
        input: "Booking question",
        context: "Reservation context",
        output: "Team response",
      },
      {
        label: "Guest requests",
        title: "Keep the next step clear behind the scenes.",
        body: "Capture guest needs and hand them to the team responsible for arranging the service.",
        input: "Guest request",
        context: "Request summary",
        output: "Service assignment",
      },
      {
        label: "Team coordination",
        title: "Carry context between shifts.",
        body: "Prepare open-item summaries so the next team can pick up outstanding conversations.",
        input: "Shift handoff",
        context: "Open requests",
        output: "Next-team summary",
      },
    ],
  },
  {
    slug: "pharmaceutical",
    name: "Pharmaceutical",
    group: "industry",
    headline: "Connect the operations behind the science.",
    description:
      "Organize administrative inquiries, documentation requests and team coordination around clear review steps.",
    request: "A partner asks for an update on a documentation request.",
    team: "Operations support",
    steps: [
      "Identify the document request",
      "Gather the administrative context",
      "Route to the document owner",
    ],
    surface: "#eae3f9",
    workflows: [
      {
        label: "Documentation requests",
        title: "Make preparation easier to review.",
        body: "Collect requested items and flag outstanding information for the responsible document team.",
        input: "Document inquiry",
        context: "Preparation checklist",
        output: "Owner review",
      },
      {
        label: "Partner communication",
        title: "Keep follow-ups connected to the source.",
        body: "Prepare summaries of partner correspondence and route specialist questions to the right team.",
        input: "Partner message",
        context: "Conversation summary",
        output: "Specialist handoff",
      },
      {
        label: "Internal coordination",
        title: "Give operational questions a destination.",
        body: "Organize administrative requests and make the next owner visible across teams.",
        input: "Internal request",
        context: "Request context",
        output: "Team assignment",
      },
    ],
  },
  {
    slug: "technology-software",
    name: "Technology & Software",
    group: "industry",
    headline: "Connect customer conversations to product work.",
    description:
      "Bring support requests, product feedback and onboarding follow-ups into one workspace.",
    request: "A customer reports an issue and shares steps to reproduce it.",
    team: "Customer operations",
    steps: [
      "Collect the issue details",
      "Prepare a reproduction summary",
      "Route for technical review",
    ],
    surface: "#f1f8dc",
    workflows: [
      {
        label: "Support triage",
        title: "Give technical teams useful context.",
        body: "Prepare the reported issue, supplied details and open questions before escalating.",
        input: "Support report",
        context: "Reproduction summary",
        output: "Technical handoff",
      },
      {
        label: "Product feedback",
        title: "Find the pattern behind the requests.",
        body: "Group related customer conversations so the product team can review recurring needs.",
        input: "Feature request",
        context: "Related feedback",
        output: "Product summary",
      },
      {
        label: "Customer onboarding",
        title: "Keep new customers moving forward.",
        body: "Organize onboarding questions and assign follow-ups to the right person.",
        input: "Onboarding question",
        context: "Open actions",
        output: "Success-team follow-up",
      },
    ],
  },
  {
    slug: "private-equity",
    name: "Private Equity",
    group: "industry",
    headline: "Bring clarity to portfolio coordination.",
    description:
      "Connect diligence requests, portfolio updates and internal handoffs without losing the underlying context.",
    request: "A portfolio team requests supporting information for a review.",
    team: "Portfolio operations",
    steps: [
      "Gather the information request",
      "Organize the outstanding items",
      "Assign the review owner",
    ],
    surface: "#e5f9f9",
    workflows: [
      {
        label: "Diligence coordination",
        title: "Keep requests and responses together.",
        body: "Organize requested materials and outstanding questions for the team conducting the review.",
        input: "Information request",
        context: "Document checklist",
        output: "Review preparation",
      },
      {
        label: "Portfolio updates",
        title: "Prepare a clearer operating picture.",
        body: "Collect supplied updates and open items into a summary for the portfolio team.",
        input: "Company update",
        context: "Operating summary",
        output: "Team review",
      },
      {
        label: "Internal handoffs",
        title: "Carry the context into the next discussion.",
        body: "Prepare a handoff of correspondence, supporting files and the next questions to resolve.",
        input: "Team handoff",
        context: "Supporting context",
        output: "Assigned follow-up",
      },
    ],
  },
  {
    slug: "cross-industry",
    name: "Cross-industry",
    group: "industry",
    headline: "One connected flow. Many ways to work.",
    description:
      "Start with the conversations, requests and handoffs your team handles every day, whatever your industry.",
    request: "A customer request needs input from two different teams.",
    team: "Operations team",
    steps: [
      "Understand the request",
      "Prepare the shared context",
      "Assign the next step",
    ],
    surface: "#d3e5ff",
    workflows: [
      {
        label: "Shared inbox work",
        title: "Bring the conversation into focus.",
        body: "Organize incoming questions and prepare the context your team needs to respond.",
        input: "Incoming question",
        context: "Conversation summary",
        output: "Response draft",
      },
      {
        label: "Team handoffs",
        title: "Keep the next action clear.",
        body: "Route requests with a useful summary and keep unresolved questions visible.",
        input: "Team request",
        context: "Handoff context",
        output: "Owner assignment",
      },
      {
        label: "Knowledge support",
        title: "Make information easier to use.",
        body: "Bring relevant approved material into the workflow before your team reviews the response.",
        input: "Information request",
        context: "Knowledge context",
        output: "Reviewed answer",
      },
    ],
  },
  {
    slug: "hr-recruitment",
    name: "HR & Recruitment",
    group: "solution",
    headline: "More time for people. Clearer next steps.",
    description:
      "Connect employee questions, hiring coordination and onboarding preparation across your people team.",
    request:
      "A new employee asks which onboarding tasks are still outstanding.",
    team: "People operations",
    steps: [
      "Gather the onboarding question",
      "Prepare the task summary",
      "Route to the people team",
    ],
    surface: "#eae3f9",
    workflows: [
      {
        label: "Employee questions",
        title: "Make approved guidance easier to find.",
        body: "Prepare responses from your internal material and route sensitive questions to the people team.",
        input: "Employee question",
        context: "Approved guidance",
        output: "HR review",
      },
      {
        label: "Hiring coordination",
        title: "Keep communication moving between people.",
        body: "Organize interview questions, scheduling correspondence and team follow-ups.",
        input: "Interview request",
        context: "Scheduling context",
        output: "Coordinator follow-up",
      },
      {
        label: "Onboarding preparation",
        title: "Give new starters a clear next step.",
        body: "Collect outstanding tasks and prepare a summary for the person coordinating onboarding.",
        input: "New-starter question",
        context: "Task checklist",
        output: "People-team handoff",
      },
    ],
  },
  {
    slug: "customer-service",
    name: "Customer Service",
    group: "solution",
    headline: "Help your team pick up with context.",
    description:
      "Bring incoming questions, knowledge and escalation handoffs into one connected service workflow.",
    request:
      "A customer follows up on a question from an earlier conversation.",
    team: "Customer service",
    steps: [
      "Gather the conversation",
      "Find relevant approved information",
      "Prepare the next response",
    ],
    surface: "#f1f8dc",
    workflows: [
      {
        label: "Incoming questions",
        title: "Find the request behind the message.",
        body: "Organize the conversation and identify what needs an answer before assigning the next step.",
        input: "Customer message",
        context: "Request summary",
        output: "Service assignment",
      },
      {
        label: "Response preparation",
        title: "Keep knowledge close to the conversation.",
        body: "Bring relevant material into a draft for your team to review before sending.",
        input: "Service question",
        context: "Knowledge reference",
        output: "Response draft",
      },
      {
        label: "Escalations",
        title: "Give specialists the context they need.",
        body: "Summarize the issue and prior actions so the next team can continue the work.",
        input: "Escalated issue",
        context: "Actions so far",
        output: "Specialist handoff",
      },
    ],
  },
  {
    slug: "debt-collection",
    name: "Debt Collection",
    group: "solution",
    headline: "Keep account follow-ups clear and considered.",
    description:
      "Organize account correspondence, response preparation and specialist handoffs with human review.",
    request: "An account holder asks a question about a payment reminder.",
    team: "Account support",
    steps: [
      "Capture the account question",
      "Prepare the correspondence summary",
      "Route for specialist review",
    ],
    surface: "#e5f9f9",
    workflows: [
      {
        label: "Account inquiries",
        title: "Keep questions tied to the conversation.",
        body: "Collect correspondence and open questions so staff can review the account holder's request.",
        input: "Account question",
        context: "Message history",
        output: "Staff review",
      },
      {
        label: "Follow-up preparation",
        title: "Review the message before it goes out.",
        body: "Prepare follow-up drafts from approved information and keep outreach decisions with your team.",
        input: "Follow-up request",
        context: "Approved context",
        output: "Reviewed draft",
      },
      {
        label: "Specialist handoffs",
        title: "Give sensitive requests a clear route.",
        body: "Summarize the request and route disputes or support needs to an appropriate person.",
        input: "Support request",
        context: "Request summary",
        output: "Specialist assignment",
      },
    ],
  },
  {
    slug: "talent-acquisition",
    name: "Talent Acquisition",
    group: "solution",
    headline: "Keep hiring conversations moving.",
    description:
      "Connect candidate communication, interview coordination and recruiter handoffs throughout the hiring process.",
    request: "A candidate asks to find another time for an interview.",
    team: "Recruiting coordination",
    steps: [
      "Gather the candidate request",
      "Prepare the scheduling context",
      "Route to the recruiter",
    ],
    surface: "#d3e5ff",
    workflows: [
      {
        label: "Candidate communication",
        title: "Make follow-ups feel connected.",
        body: "Keep correspondence and outstanding questions together for the recruiter handling the conversation.",
        input: "Candidate message",
        context: "Conversation context",
        output: "Recruiter response",
      },
      {
        label: "Interview coordination",
        title: "Make the next scheduling step clear.",
        body: "Organize availability questions and prepare the information needed to coordinate the interview.",
        input: "Scheduling request",
        context: "Availability context",
        output: "Coordinator handoff",
      },
      {
        label: "Recruiter handoffs",
        title: "Help the next person get up to speed.",
        body: "Summarize administrative context and open actions while keeping hiring decisions with people.",
        input: "Recruiter handoff",
        context: "Open-action summary",
        output: "Assigned follow-up",
      },
    ],
  },
  {
    slug: "custom-ai-solutions",
    name: "Custom AI Solutions",
    group: "solution",
    headline: "Shape the workflow around your team.",
    description:
      "Start with a real process, map the handoffs and explore where agents can help your people do the work.",
    request:
      "Your team wants to connect a recurring request to its internal tools.",
    team: "Workflow design",
    steps: [
      "Map the current process",
      "Identify context and review points",
      "Plan a focused pilot",
    ],
    surface: "#eae3f9",
    workflows: [
      {
        label: "Process discovery",
        title: "Start with the work as it happens today.",
        body: "Identify the trigger, information, owners and exceptions that define the workflow.",
        input: "Process walkthrough",
        context: "Workflow map",
        output: "Pilot scope",
      },
      {
        label: "Connected context",
        title: "Plan the information each step needs.",
        body: "Review the tools and sources involved before deciding how a connection should work.",
        input: "Tool inventory",
        context: "Context requirements",
        output: "Connection plan",
      },
      {
        label: "Pilot design",
        title: "Make review part of the process.",
        body: "Define handoffs and success criteria with your team before expanding the workflow.",
        input: "Pilot proposal",
        context: "Review checkpoints",
        output: "Team evaluation",
      },
    ],
  },
];

export function getIndustryPage(slug: string) {
  return industryPages.find((page) => page.slug === slug);
}
export const industryHref = (slug: string) => `/industries/${slug}`;
