// Badge artwork and destinations from Notion's Product Launch Directories.
// Snapshot: 2026-09-11. Some submissions await a published backlink.
export const launchDirectories = [
  {
    name: "ConfettiSaaS",
    href: "https://confettisaas.com/saas/innflow-ai?ref=badge",
    src: "https://confettisaas.com/badge-light.svg",
    width: 250,
    height: 54,
    nofollow: false,
  },
  {
    name: "DodoDirectory",
    href: "https://dododirectory.com",
    src: "https://dododirectory.com/badge-light.png",
    width: 200,
    height: 54,
    nofollow: false,
  },
  {
    name: "EarlyHunt",
    href: "https://earlyhunt.com/project/innflow",
    src: "https://earlyhunt.com/badges/earlyhunt-badge-light.svg",
    width: 300,
    height: 68,
    nofollow: false,
  },
  {
    name: "Fazier",
    href: "https://fazier.com",
    src: "https://fazier.com/api/v1/public/badges/launch_badges.svg?badge_type=launched&theme=light",
    width: 120,
    height: 54,
    nofollow: false,
  },
  {
    name: "findly.tools",
    href: "https://findly.tools",
    src: "https://findly.tools/badges/findly-tools-badge-light.svg",
    width: 205,
    height: 65,
    nofollow: false,
  },
  {
    name: "Huzzler",
    href: "https://huzzler.so",
    src: "https://huzzler.so/assets/images/embeddable-badges/featured.png",
    width: 220,
    height: 54,
    nofollow: false,
  },
  {
    name: "IdeaKiln",
    href: "https://ideakiln.com",
    src: "https://ideakiln.com/light.svg",
    width: 200,
    height: 54,
    nofollow: false,
  },
  {
    name: "Indiehunt",
    href: "https://indiehunt.io",
    src: "https://indiehunt.io/badges/indiehunt-badge-light.svg",
    width: 300,
    height: 68,
    nofollow: false,
  },
  {
    name: "Launch Llama Tools",
    href: "https://tools.launchllama.co?utm_source=badge&utm_medium=referral",
    src: "https://tools.launchllama.co/featured-badge.png?v=2",
    width: 200,
    height: 50,
    nofollow: false,
  },
  {
    name: "neeed.directory",
    href: "https://neeed.directory/products/innflow?utm_source=innflow",
    src: "https://neeed.directory/badges/neeed-badge-light.svg",
    width: 139,
    height: 54,
    nofollow: false,
  },
  {
    name: "SaaSBison",
    href: "https://saasbison.com",
    src: "https://saasbison.com/badge.png",
    width: 220,
    height: 54,
    nofollow: false,
  },
  {
    name: "SaaSGrow",
    href: "https://saasgrow.app?ref=innflow.ai",
    src: "https://saasgrow.app/api/badge?type=featured&style=light",
    width: 240,
    height: 54,
    nofollow: false,
  },
  {
    name: "StartupBase",
    href: "https://startupbase.io",
    src: "https://statics.startupbase.io/site/badges/featured-on-sb.svg",
    width: 190,
    height: 44,
    nofollow: false,
  },
  {
    name: "StartupFA.me",
    href: "https://startupfa.me/s/innflow.ai-345?utm_source=innflow.ai",
    src: "https://startupfa.me/badges/featured-badge-small.webp",
    width: 224,
    height: 36,
    nofollow: false,
  },
  {
    name: "startupfa.st",
    href: "https://startupfa.st",
    src: "https://startupfa.st/images/badges/powered-by-light.svg",
    width: 150,
    height: 44,
    nofollow: true,
  },
  {
    name: "Sumodir",
    href: "https://sumodir.com",
    src: "https://sumodir.com/badge.png",
    width: 200,
    height: 54,
    nofollow: false,
  },
  {
    name: "TechTrendin",
    href: "https://www.techtrendin.com/products/innflow",
    src: "https://www.techtrendin.com/badges/featured-light.png",
    width: 220,
    height: 54,
    nofollow: false,
  },
  {
    name: "Twelve Tools",
    href: "https://twelve.tools",
    src: "https://twelve.tools/badge0-light.svg",
    width: 200,
    height: 54,
    nofollow: false,
  },
  {
    name: "Web Review",
    href: "https://web-review.com",
    src: "https://web-review.com/badge.png",
    width: 220,
    height: 54,
    nofollow: false,
  },
] as const;
