// Official badge HTML from Notion's Product Launch Directories.
// Verified 2026-09-28. Keep href, src, alt and backlink relationships intact.
// Pending records require a homepage badge before submission or approval.
export const launchDirectories = [
  {
    name: "Bowora",
    // Add Innflow's via code once Bowora creates the listing.
    href: "https://bowora.com/",
    src: "https://bowora.com/api/badge?startup=innflow.ai&theme=light",
    alt: "Featured on Bowora",
    width: 210,
    height: 50,
    rel: "noopener",
    status: "pending",
    source: "https://app.notion.com/37e0ac1bd32e8137b7f3f62173687e21",
  },
  {
    name: "ConfettiSaaS",
    href: "https://confettisaas.com/saas/innflow-ai?ref=badge",
    src: "https://confettisaas.com/badge-light.svg",
    alt: "Innflow on ConfettiSaaS",
    width: 250,
    height: 54,
    rel: "noopener",
    status: "pending",
    source: "https://app.notion.com/37e0ac1bd32e8183ab9fc72c441c56cf",
  },
  {
    name: "DodoDirectory",
    href: "https://dododirectory.com",
    src: "https://dododirectory.com/badge-light.png",
    alt: "Featured on DodoDirectory",
    width: 200,
    height: 54,
    rel: "dofollow noopener",
    status: "pending",
    source: "https://app.notion.com/37e0ac1bd32e81eebe50e28fa896c3bf",
  },
  {
    name: "EarlyHunt",
    href: "https://earlyhunt.com/project/innflow",
    src: "https://earlyhunt.com/badges/earlyhunt-badge-light.svg",
    alt: "Featured on EarlyHunt",
    width: 300,
    height: 68,
    rel: "noopener",
    status: "listed",
    source: "https://app.notion.com/37e0ac1bd32e81cd88e0e2ad2e71db1b",
  },
  {
    name: "Fazier",
    href: "https://fazier.com",
    src: "https://fazier.com/api/v1/public/badges/launch_badges.svg?badge_type=launched&theme=light",
    alt: "Fazier badge",
    width: 120,
    height: 54,
    rel: "noopener",
    status: "pending",
    source: "https://app.notion.com/37e0ac1bd32e81098558dadfafcb04cb",
  },
  {
    name: "findly.tools",
    href: "https://findly.tools",
    src: "https://findly.tools/badges/findly-tools-badge-light.svg",
    alt: "Featured on Findly.tools",
    width: 205,
    height: 65,
    rel: "noopener noreferrer",
    status: "pending",
    source: "https://app.notion.com/37e0ac1bd32e8140b062c3ad91991d50",
  },
  {
    name: "Huzzler",
    href: "https://huzzler.so",
    src: "https://huzzler.so/assets/images/embeddable-badges/featured.png",
    alt: "Featured on Huzzler",
    width: 220,
    height: 54,
    rel: "noopener noreferrer",
    status: "pending",
    source: "https://app.notion.com/37e0ac1bd32e81a09789df7887109242",
  },
  {
    name: "IdeaKiln",
    href: "https://ideakiln.com",
    src: "https://ideakiln.com/light.svg",
    alt: "Featured on Idea Kiln",
    width: 200,
    height: 54,
    rel: "noopener",
    status: "pending",
    source: "https://app.notion.com/37e0ac1bd32e81b3b0dfeb03b08f4484",
  },
  {
    name: "Indiehunt",
    href: "https://indiehunt.io",
    src: "https://indiehunt.io/badges/indiehunt-badge-light.svg",
    alt: "Featured on IndieHunt",
    width: 300,
    height: 68,
    rel: "noopener",
    status: "pending",
    source: "https://app.notion.com/37e0ac1bd32e8106b401e13316100747",
  },
  {
    name: "Launch Llama Tools",
    href: "https://tools.launchllama.co?utm_source=badge&utm_medium=referral",
    src: "https://tools.launchllama.co/featured-badge.png?v=2",
    alt: "As seen on Launch Llama Newsletter",
    width: 200,
    height: 50,
    rel: "noopener noreferrer",
    status: "pending",
    source: "https://app.notion.com/37e0ac1bd32e81ffbcb4e2ccbbb984e9",
  },
  {
    name: "neeed.directory",
    href: "https://neeed.directory/products/innflow?utm_source=innflow",
    src: "https://neeed.directory/badges/neeed-badge-light.svg",
    alt: "Featured on neeed.directory",
    width: 139,
    height: 54,
    rel: "noopener",
    status: "listed",
    source: "https://app.notion.com/37e0ac1bd32e812d9930f25a4b6aa675",
  },
  {
    name: "SaaSBison",
    href: "https://saasbison.com",
    src: "https://saasbison.com/badge.png",
    alt: "Featured on SaaSBison",
    width: 220,
    height: 54,
    rel: "noopener noreferrer",
    status: "pending",
    source: "https://app.notion.com/37e0ac1bd32e81419629dc525511ff8e",
  },
  {
    name: "SaaSGrow",
    href: "https://saasgrow.app?ref=innflow.ai",
    src: "https://saasgrow.app/api/badge?type=featured&style=light",
    alt: "Innflow on SaaSGrow",
    width: 240,
    height: 54,
    rel: "noopener",
    status: "pending",
    source: "https://app.notion.com/37e0ac1bd32e81bc8837cc57250a580f",
  },
  {
    name: "StartupBase",
    href: "https://startupbase.io",
    src: "https://statics.startupbase.io/site/badges/featured-on-sb.svg",
    alt: "Featured on StartupBase",
    width: 190,
    height: 44,
    rel: "noopener noreferrer",
    status: "pending",
    source: "https://app.notion.com/37e0ac1bd32e815a96e7efe7916ce4ec",
  },
  {
    name: "StartupFA.me",
    href: "https://startupfa.me/s/innflow.ai-345?utm_source=innflow.ai",
    src: "https://startupfa.me/badges/featured-badge-small.webp",
    alt: "Featured on Startup Fame",
    width: 224,
    height: 36,
    rel: "noopener",
    status: "listed",
    source: "https://app.notion.com/37e0ac1bd32e81c6bb89d5525ed7d93b",
  },
  {
    name: "startupfa.st",
    href: "https://startupfa.st",
    src: "https://startupfa.st/images/badges/powered-by-light.svg",
    alt: "Powered by Startup Fast",
    width: 150,
    height: 44,
    rel: "noopener",
    status: "pending",
    source: "https://app.notion.com/37e0ac1bd32e81d298cfef1de260dce8",
  },
  {
    name: "Sumodir",
    href: "https://sumodir.com",
    src: "https://sumodir.com/badge.png",
    alt: "Featured on SumoDir",
    width: 200,
    height: 54,
    rel: "dofollow noopener",
    status: "pending",
    source: "https://app.notion.com/37e0ac1bd32e81559f9de6bed904082a",
  },
  {
    name: "TechTrendin",
    href: "https://www.techtrendin.com/products/innflow",
    src: "https://www.techtrendin.com/badges/featured-light.png",
    alt: "Featured on TechTrendin",
    width: 220,
    height: 54,
    rel: "noopener",
    status: "listed",
    source: "https://app.notion.com/37e0ac1bd32e818786cacb32663c9c1c",
  },
  {
    name: "Twelve Tools",
    href: "https://twelve.tools",
    src: "https://twelve.tools/badge0-light.svg",
    alt: "Featured on Twelve Tools",
    width: 200,
    height: 54,
    rel: "noopener",
    status: "pending",
    source: "https://app.notion.com/37e0ac1bd32e81cc816cec703b511c7f",
  },
  {
    name: "Web Review",
    href: "https://web-review.com",
    src: "https://web-review.com/badge.png",
    alt: "Featured on Web Review",
    width: 220,
    height: 54,
    rel: "noopener noreferrer",
    status: "pending",
    source: "https://app.notion.com/37e0ac1bd32e81489e32c5f3da0ea30d",
  },
] as const;
