import type { PlatformDetail } from "./platform-details";

export const remainingPlatformDetails: Record<string, PlatformDetail> = {
  evaluations: {
    slug: "evaluations",
    title: "Evaluations",
    headline: "Know how well your agents handle the work.",
    description:
      "Evaluate the outcome, inspect the steps, and turn findings into focused improvements with innflow.",
    intro: "Make quality visible at every level.",
    hero: "/brand/platform/evaluations/hero.png",
    heroAlt: "Blue evaluation checkmark above stacked blocks",
    capabilities: [
      {
        id: "accuracy",
        label: "Three-layer accuracy",
        title: "See where a result needs attention.",
        body: "Review the whole task, the individual step, and the fields in its output. Trace an incorrect invoice total back to the source that produced it.",
        points: [
          "Workflow outcomes",
          "Step-level review",
          "Field-level checks",
        ],
        image: "/brand/platform/evaluations/accuracy.png",
        alt: "Three-layer accuracy interface illustration",
      },
      {
        id: "benchmarks",
        label: "Human benchmarks",
        title: "Set a useful baseline.",
        body: "Compare an agent result with a reviewed example from your team. Use the same inputs and expectations to make the comparison meaningful.",
        points: [
          "Reviewed examples",
          "Consistent criteria",
          "Comparable outcomes",
        ],
        image: "/brand/platform/evaluations/benchmarks.png",
        alt: "Human benchmarks interface illustration",
      },
      {
        id: "retry",
        label: "Retry and recovery",
        title: "Give incomplete work a clear next step.",
        body: "Decide which failures can be retried and which need a person. Keep limits and recovery behavior explicit before a process runs repeatedly.",
        points: ["Retry limits", "Failure context", "Human escalation"],
        image: "/brand/platform/evaluations/retry.png",
        alt: "Retry and recovery interface illustration",
      },
      {
        id: "criteria",
        label: "Evaluation criteria",
        title: "Define what a correct answer includes.",
        body: "Specify the fields, formats, and business rules that matter to your operation. A valid date and a matching invoice total are concrete places to start.",
        points: ["Required fields", "Format checks", "Business rules"],
        image: "/brand/platform/evaluations/criteria.png",
        alt: "Evaluation criteria interface illustration",
      },
      {
        id: "datasets",
        label: "Test datasets",
        title: "Test against the work you expect.",
        body: "Collect representative requests with reviewed answers. Include the routine cases and the awkward exceptions that expose gaps before your team relies on a workflow.",
        points: [
          "Representative inputs",
          "Expected answers",
          "Version comparison",
        ],
        image: "/brand/platform/evaluations/datasets-innflow.png",
        alt: "Test datasets interface illustration",
      },
      {
        id: "feedback",
        label: "Feedback loops",
        title: "Connect review to the next improvement.",
        body: "Preserve corrections alongside the original result. Give reviewers a way to explain what was missing and carry that context into the next iteration.",
        points: [
          "Review in context",
          "Capture corrections",
          "Refine instructions",
        ],
        image: "/brand/platform/evaluations/feedback.png",
        alt: "Feedback loops interface illustration",
      },
      {
        id: "dashboards",
        label: "Quality dashboards",
        title: "Look beyond a completed-task count.",
        body: "Review quality alongside volume and turnaround time. A workflow that finishes quickly still needs to deliver the right information to the right person.",
        points: ["Quality trends", "Completion context", "Time comparisons"],
        image: "/brand/platform/evaluations/dashboards.png",
        alt: "Quality dashboards interface illustration",
      },
      {
        id: "reporting",
        label: "Team reporting",
        title: "Share the evidence behind progress.",
        body: "Bring the evaluation results and supporting examples into your operational review. Make it clear what improved, what remains uncertain, and who owns the next change.",
        points: ["Review summaries", "Supporting examples", "Clear ownership"],
        image: "/brand/platform/evaluations/reporting.png",
        alt: "Team reporting interface illustration",
      },
    ],
  },
  "analytics-and-observability": {
    slug: "analytics-and-observability",
    title: "Analytics and Observability",
    headline: "Understand every step of your agent workflows.",
    description:
      "Bring outcomes, execution context, and resource use into one operational picture with innflow.",
    intro: "Follow the work from activity to outcome.",
    hero: "/brand/platform/analytics-and-observability/hero.png",
    heroAlt: "Blue columns representing agent performance analytics",
    capabilities: [
      {
        id: "performance",
        label: "Performance dashboards",
        title: "See how the operation is moving.",
        body: "Review completed work, exceptions, and time spent together. Choose a consistent period so changes in activity have a useful comparison.",
        points: ["Task outcomes", "Review periods", "Runtime trends"],
        image: "/brand/platform/analytics-and-observability/performance.png",
        alt: "Performance dashboards interface illustration",
      },
      {
        id: "accuracy",
        label: "Accuracy measurement",
        title: "Find the source of an incorrect result.",
        body: "Inspect a task at workflow, step, and output level. Connect a reported issue to the input and decision that need review.",
        points: ["Workflow review", "Step inspection", "Output checks"],
        image: "/brand/platform/analytics-and-observability/accuracy.png",
        alt: "Accuracy measurement interface illustration",
      },
      {
        id: "traces",
        label: "Execution tracing",
        title: "Follow the full sequence.",
        body: "Keep the trigger, inputs, actions, and resulting handoff connected. Use the sequence to explain a delay or understand why a request reached a particular team.",
        points: ["Execution timeline", "Input context", "Action history"],
        image: "/brand/platform/analytics-and-observability/traces-innflow.png",
        alt: "Execution tracing interface illustration",
      },
      {
        id: "logs",
        label: "Observability and logs",
        title: "Bring technical signals into the investigation.",
        body: "Review errors and timing beside the task they affected. Give the people investigating a problem enough context to distinguish a slow dependency from a workflow issue.",
        points: ["Error context", "Timing signals", "Dependency review"],
        image: "/brand/platform/analytics-and-observability/logs-innflow.png",
        alt: "Observability and logs interface illustration",
      },
      {
        id: "costs",
        label: "Cost tracking",
        title: "Understand the resources behind the work.",
        body: "Compare resource use across recurring operations. Review unusually expensive tasks alongside their complexity and quality before deciding what to change.",
        points: [
          "Usage patterns",
          "Task comparisons",
          "Optimization priorities",
        ],
        image: "/brand/platform/analytics-and-observability/costs.png",
        alt: "Cost tracking interface illustration",
      },
      {
        id: "learning",
        label: "Learning analytics",
        title: "Track what changes after a correction.",
        body: "Compare reviewed outcomes before and after an instruction update. Keep examples close to the trend so your team can explain the difference.",
        points: [
          "Before-and-after review",
          "Quality trends",
          "Correction history",
        ],
        image: "/brand/platform/self-learning/hub-innflow.png",
        alt: "Learning analytics interface illustration",
      },
      {
        id: "fleet",
        label: "Agent fleet",
        title: "Review the whole team of agents.",
        body: "Look across workflows to find common issues and uneven workloads. Assign attention where an agent or connection needs support.",
        points: [
          "Cross-workflow view",
          "Agent comparisons",
          "Connection health",
        ],
        image: "/brand/platform/analytics-and-observability/fleet-innflow.png",
        alt: "Agent fleet interface illustration",
      },
      {
        id: "metrics",
        label: "Metrics access",
        title: "Use operational data in your reporting.",
        body: "Plan the measures and reporting destinations your team needs. Confirm available data and access before connecting a new reporting workflow.",
        points: [
          "Shared definitions",
          "Reporting destinations",
          "Scoped access",
        ],
        image:
          "/brand/platform/analytics-and-observability/metrics-innflow.png",
        alt: "Metrics access interface illustration",
      },
    ],
  },
  integrations: {
    slug: "integrations",
    title: "Integrations",
    headline: "Connect innflow to the systems behind your work.",
    description:
      "Bring tools, records, and workflow actions together around the operations your property team runs every day.",
    intro: "Make every connection useful.",
    hero: "/brand/platform/integrations/hero.png",
    heroAlt: "Blue lightning bolt representing connected tools",
    capabilities: [
      {
        id: "connectors",
        label: "Native connectors",
        title: "Start with the tools your team uses.",
        body: "Map your inbox, shared files, and property systems to the operation. Confirm the available connector actions before designing each handoff.",
        points: ["Connected accounts", "Available actions", "System ownership"],
        image: "/brand/platform/integrations/connectors.png",
        alt: "Native connectors interface illustration",
      },
      {
        id: "custom",
        label: "Custom integrations",
        title: "Make room for your internal systems.",
        body: "Document the endpoints and data your workflow needs. Use an API specification as a starting point for scoping a connection to a custom service.",
        points: ["API specifications", "Required endpoints", "Data contracts"],
        image: "/brand/platform/integrations/custom-innflow.png",
        alt: "Custom integrations interface illustration",
      },
      {
        id: "authentication",
        label: "Authentication",
        title: "Give each connection the right access.",
        body: "Connect the account responsible for the operation. Review its permissions and credential lifecycle before allowing a workflow to use it.",
        points: [
          "Account permissions",
          "Credential lifecycle",
          "Connection review",
        ],
        image: "/brand/platform/integrations/authentication.png",
        alt: "Authentication interface illustration",
      },
      {
        id: "browser",
        label: "Browser actions",
        title: "Plan for tools that need a browser.",
        body: "Some tasks still happen through an interface. Identify the pages and review points involved, and account for changes in layout or sign-in behavior.",
        points: [
          "Interface steps",
          "Sign-in requirements",
          "Maintenance ownership",
        ],
        image: "/brand/platform/integrations/browser.png",
        alt: "Browser actions interface illustration",
      },
      {
        id: "actions",
        label: "Action execution",
        title: "Turn context into a clear action.",
        body: "Map the information collected by the workflow to the fields an action expects. Review missing inputs and failure handling before the next system is updated.",
        points: ["Parameter mapping", "Input validation", "Failure handling"],
        image: "/brand/platform/integrations/actions.png",
        alt: "Action execution interface illustration",
      },
      {
        id: "mcp",
        label: "MCP connections",
        title: "Connect tools through a common interface.",
        body: "Explore how an MCP connection can expose the tools a workflow needs. Confirm authentication, available operations, and the boundary of access for each connection.",
        points: [
          "Tool discovery",
          "Authentication scope",
          "Operation boundaries",
        ],
        image: "/brand/platform/integrations/mcp.png",
        alt: "MCP connections interface illustration",
      },
      {
        id: "skills",
        label: "Reusable skills",
        title: "Group actions around a useful task.",
        body: "Organize related operations into a reusable skill. Keep the instructions and expected inputs clear so another workflow can use the same capability consistently.",
        points: [
          "Reusable instructions",
          "Expected inputs",
          "Focused capabilities",
        ],
        image: "/brand/platform/integrations/skills.png",
        alt: "Reusable skills interface illustration",
      },
      {
        id: "permissions",
        label: "Integration security",
        title: "Keep access tied to the connected account.",
        body: "Review provider permissions alongside the actions your team intends to allow. Revisit the connection when responsibilities or access requirements change.",
        points: ["Provider permissions", "Allowed operations", "Access review"],
        image: "/brand/platform/integrations/permissions-innflow.png",
        alt: "Integration security interface illustration",
      },
    ],
  },
  "deployment-options": {
    slug: "deployment-options",
    title: "Deployment Options",
    headline: "Plan where and how your agents run.",
    description:
      "Discuss the environment, ownership, and infrastructure requirements for bringing innflow into your operation.",
    intro: "Match deployment to your team’s requirements.",
    hero: "/brand/platform/deployment-options/hero.png",
    heroAlt: "Blue network hub representing deployment environments",
    capabilities: [
      {
        id: "cloud",
        label: "Cloud deployment",
        title: "Start with the operational requirements.",
        body: "Discuss the hosting environment, expected workload, and services your workflow depends on. Establish how updates and day-to-day support will be handled.",
        points: [
          "Hosting requirements",
          "Workload expectations",
          "Support ownership",
        ],
        image: "/brand/platform/deployment-options/cloud.jpg",
        alt: "Cloud deployment interface illustration",
      },
      {
        id: "private",
        label: "Private environments",
        title: "Define the boundaries of a dedicated setup.",
        body: "Work through network access, account ownership, and isolation requirements with your infrastructure team. Confirm the deployment scope before implementation.",
        points: [
          "Network boundaries",
          "Account ownership",
          "Implementation scope",
        ],
        image: "/brand/platform/deployment-options/private-innflow.png",
        alt: "Private environments interface illustration",
      },
      {
        id: "on-premise",
        label: "On-premise requirements",
        title: "Map responsibilities within your environment.",
        body: "For infrastructure you operate, define the hardware, service dependencies, and maintenance responsibilities. Review feasibility against the needs of the intended workflow.",
        points: [
          "Infrastructure inventory",
          "Service dependencies",
          "Maintenance plan",
        ],
        image: "/brand/platform/deployment-options/on-premise-innflow.png",
        alt: "On-premise requirements interface illustration",
      },
      {
        id: "models",
        label: "Model connections",
        title: "Choose model access deliberately.",
        body: "Review the model endpoints, data handling requirements, and credentials involved in an operation. Match the proposed setup to the task and its constraints.",
        points: [
          "Endpoint requirements",
          "Data handling",
          "Credential ownership",
        ],
        image: "/brand/platform/deployment-options/models.jpg",
        alt: "Model connections interface illustration",
      },
      {
        id: "regions",
        label: "Regional requirements",
        title: "Account for where data needs to stay.",
        body: "Document the locations involved in storage, processing, and support. Bring residency requirements into the deployment discussion before choosing an environment.",
        points: [
          "Data locations",
          "Processing requirements",
          "Regional review",
        ],
        image: "/brand/platform/deployment-options/regions.jpg",
        alt: "Regional requirements interface illustration",
      },
      {
        id: "migration",
        label: "Migration planning",
        title: "Prepare for a change of environment.",
        body: "Inventory workflow configuration and connected accounts before a move. Plan validation, cutover, and recovery so the transition has a clear owner.",
        points: ["Configuration inventory", "Cutover plan", "Recovery path"],
        image: "/brand/platform/deployment-options/migration-innflow.png",
        alt: "Migration planning interface illustration",
      },
      {
        id: "governance",
        label: "Deployment governance",
        title: "Agree on the controls the environment needs.",
        body: "Review the evidence required by your organization and the responsibilities of each provider. Confirm applicable controls as part of deployment planning.",
        points: [
          "Control requirements",
          "Provider responsibilities",
          "Evidence review",
        ],
        image: "/brand/platform/deployment-options/governance.jpg",
        alt: "Deployment governance interface illustration",
      },
      {
        id: "support",
        label: "Implementation support",
        title: "Bring the right people into the rollout.",
        body: "Coordinate the operational team, system owners, and implementation contacts. Work from a shared checklist for connections, validation, and ongoing support.",
        points: ["Named contacts", "Rollout checklist", "Team handover"],
        image: "/brand/platform/deployment-options/support-innflow.png",
        alt: "Implementation support interface illustration",
      },
    ],
  },
  "security-and-compliance": {
    slug: "security-and-compliance",
    title: "Security and Compliance",
    headline: "Build trust into the way work gets done.",
    description:
      "Explore access, data handling, and operational governance with innflow. Bring your security requirements into the conversation from the start.",
    intro: "A clear view of your security requirements.",
    hero: "/brand/platform/security-and-compliance/hero.png",
    heroAlt: "Blue shield and lock representing security controls",
    capabilities: [
      {
        id: "compliance",
        label: "Compliance review",
        title: "Start with the evidence your team needs.",
        body: "Identify the standards and documentation relevant to your organization. Request current evidence for the proposed deployment before treating a requirement as satisfied.",
        points: [
          "Applicable standards",
          "Current documentation",
          "Deployment scope",
        ],
        image: "/brand/platform/security-and-compliance/compliance.png",
        alt: "Compliance review interface illustration",
      },
      {
        id: "privacy",
        label: "Privacy and residency",
        title: "Understand where information travels.",
        body: "Map the data involved in your workflow and the services that process it. Review storage, retention, and regional requirements together.",
        points: [
          "Data flows",
          "Retention requirements",
          "Regional requirements",
        ],
        image: "/brand/platform/security-and-compliance/privacy.png",
        alt: "Privacy and residency interface illustration",
      },
      {
        id: "data",
        label: "Data protection",
        title: "Make data handling explicit.",
        body: "Review how the proposed setup handles customer information, model-provider processing, and account separation. Confirm the terms that apply to your workspace.",
        points: [
          "Provider terms",
          "Processing boundaries",
          "Account separation",
        ],
        image: "/brand/platform/security-and-compliance/data.png",
        alt: "Data protection interface illustration",
      },
      {
        id: "access",
        label: "Access control",
        title: "Match access to responsibility.",
        body: "Define who can view, change, and approve the work. Review connected-account permissions when team roles or operational responsibilities change.",
        points: [
          "Team responsibilities",
          "Connection permissions",
          "Access reviews",
        ],
        image: "/brand/platform/security-and-compliance/access.png",
        alt: "Access control interface illustration",
      },
      {
        id: "audit",
        label: "Audit and logging",
        title: "Keep actions explainable.",
        body: "Plan which events and decisions need a record. Agree on who can review that history and how long it should remain available.",
        points: ["Action history", "Review access", "Retention planning"],
        image: "/brand/platform/security-and-compliance/audit.png",
        alt: "Audit and logging interface illustration",
      },
      {
        id: "encryption",
        label: "Encryption requirements",
        title: "Review protection across the data path.",
        body: "Document the protection expected for stored information and connections between systems. Confirm the controls used by each service in the proposed environment.",
        points: ["Stored information", "System connections", "Control review"],
        image: "/brand/platform/security-and-compliance/encryption.png",
        alt: "Encryption requirements interface illustration",
      },
      {
        id: "ai-security",
        label: "AI-specific risks",
        title: "Review the inputs and actions an agent can use.",
        body: "Treat external content as information to evaluate. Define action boundaries and human review points for requests that could affect sensitive records or decisions.",
        points: ["Input handling", "Action boundaries", "Human review"],
        image: "/brand/platform/security-and-compliance/ai-security.png",
        alt: "AI-specific risks interface illustration",
      },
      {
        id: "deployment",
        label: "Deployment security",
        title: "Include infrastructure in the security review.",
        body: "Connect environment requirements to network access, operations, and recovery. Establish who maintains the controls and who responds when an issue appears.",
        points: [
          "Network requirements",
          "Operational ownership",
          "Response planning",
        ],
        image: "/brand/platform/security-and-compliance/deployment-innflow.png",
        alt: "Deployment security interface illustration",
      },
    ],
  },
};
