// Paper stroke icons, mapped by menu label rather than destination (some links share URLs).
export const blMenuIcons: Record<string, string> = {
  Platform: "/brand/navigation/bl-stroke/01-laptop.svg",
  "AI Agents": "/brand/navigation/bl-stroke/03-direction-up-right.svg",
  Copilot: "/brand/navigation/bl-stroke/04-preview.svg",
  "Agentic Workflows": "/brand/navigation/bl-stroke/05-stack.svg",
  "Agent Skills": "/brand/navigation/bl-stroke/06-settings.svg",
  "AI Website Builder": "/brand/navigation/bl-stroke/07-screencast.svg",
  Databases: "/brand/navigation/bl-stroke/08-database.svg",
  Templates: "/brand/navigation/bl-stroke/09-file-records.svg",
  Advertising: "/brand/navigation/bl-stroke/11-megaphone-a.svg",
  "Application & eSign": "/brand/navigation/bl-stroke/12-edit-pen.svg",
  CRM: "/brand/navigation/bl-stroke/13-contact-book.svg",
  Conventional: "/brand/navigation/bl-stroke/14-building-a.svg",
  "Student Housing": "/brand/navigation/bl-stroke/15-building-tree.svg",
  "Centralized Operations": "/brand/navigation/bl-stroke/16-dashboard-3.svg",
  "Owner Operators and Fee Managers":
    "/brand/navigation/bl-stroke/17-briefcase.svg",
  Owners: "/brand/navigation/bl-stroke/18-key.svg",
  "Maintenance & Mobile App": "/brand/navigation/bl-stroke/19-wrench.svg",
  "Owner Portal": "/brand/navigation/bl-stroke/20-user-square.svg",
  "Move-In": "/brand/navigation/bl-stroke/21-home-plus.svg",
  Renewals: "/brand/navigation/bl-stroke/22-calendar-check.svg",
  Delinquency: "/brand/navigation/bl-stroke/23-credit-card.svg",
  Residential: "/brand/navigation/bl-stroke/24-home.svg",
  Multifamily: "/brand/navigation/bl-stroke/25-building-b.svg",
  Commercial: "/brand/navigation/bl-stroke/26-shop.svg",
  "Community Associations": "/brand/navigation/bl-stroke/27-users.svg",
  Connections: "/brand/navigation/bl-stroke/28-share.svg",
  Integrations: "/brand/navigation/bl-stroke/28-share.svg",
  Pricing: "/brand/navigation/bl-stroke/29-tag.svg",
  Blog: "/brand/navigation/bl-stroke/30-book-text.svg",
  "Become an Affiliate": "/brand/navigation/bl-stroke/31-share.svg",
  "Customer Stories": "/brand/navigation/bl-stroke/32-user-check.svg",
  Listings: "/brand/navigation/bl-stroke/10-checklist-note.svg",
  "Asset Library": "/brand/navigation/bl-stroke/33-archive-drawer.svg",
};
